apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    database: logistics_metrics
    user: ''
    password: ''
    jsonData:
      httpMode: POST
